#!/usr/bin/env bash

PROGRAM=test

cd "$(dirname "${BASH_SOURCE[0]}")"

TRIDENT_CC="$(realpath ../../main/trident-cc)"

if [ -f "$PROGRAM" ]; then
   make clean
fi

rm -rf klee-*

CC="$TRIDENT_CC" make -e
extract-bc "$PROGRAM"
