#!/usr/bin/env bash

PROGRAM=test

cd "$(dirname "${BASH_SOURCE[0]}")"

CPR_CC="$(realpath ../../tools/cpr-cc)"

if [ -f "$PROGRAM" ]; then
   make clean
fi

rm -rf klee-*

CC="$CPR_CC" make -e
extract-bc "$PROGRAM"

klee --posix-runtime --libc=uclibc --write-smt2s --output-dir=klee-t1 "${PROGRAM}.bc" 1

# python3.6 ../CPR/app/synthesis.py \
#           --tests t1.smt2:klee-t1 t2.smt2:klee-t2 \
#           --verify L9:patch.smt2

# python3.6 ../CPR/app/synthesis.py \
#           --tests t1.smt2:klee-t1 \
#           --components components/*.smt2 ../CPR/components/less-than.smt2 ../CPR/components/constant_a.smt2 \
#           --verify L9:patch.json

python3.6 ../../main/synthesis.py \
          --tests t1.smt2:klee-t1 \
          --components components/*.smt2 ../../components/less-than.smt2 ../../components/constant_a.smt2  \
          --all --output patches
